version: "3.8"

services:
  django:
    image: django
    container_name: django
    build: .
    ports:
      - 8001:8000
    expose:
      - "8000"
    volumes:
      - .:/myproject
    networks:
      - webnet

  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: "nginx_con"
    depends_on:
      - django
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./media:/media
      - ./nginx:/etc/ssl:ro
      
    ports:
      - "80:80"
      - 443:443
    networks:
      - webnet

<<<<<<< HEAD
  
=======
>>>>>>> 13614be5b6f27a65e9ab62c5b5ccb119ad003653
networks:
  webnet:
