version: "3.8"

services:
  django:
    image: django
    container_name: django
    build: .
    ports:
      - 8001:8000
    expose:
      - "8000"
    volumes:
      - .:/myproject
    networks:
      - webnet

  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: "nginx_cont"
    depends_on:
      - django
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./media:/media
      - ./certbot-webroot:/var/www/html
    ports:
      - "80:80"
    networks:
      - webnet

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot-webroot:/var/www/html  # Temporary webroot for Certbot
    command: certonly --webroot -w /var/www/html -d dowellchat.uxlivinglab.online -d www.dowellchat.uxlivinglab.online


networks:
  webnet:
