# Generated by Django 4.1 on 2024-08-07 09:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websocket', '0003_linemanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_id', models.CharField(max_length=250, unique=True)),
                ('number_of_links', models.PositiveIntegerField()),
                ('available_links', models.PositiveIntegerField()),
                ('product_distribution', models.JSONField()),
                ('usernames', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('master_link', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websocket.workspace')),
            ],
        ),
    ]
