# Generated by Django 4.1 on 2024-08-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlink',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
