# Generated by Django 4.1 on 2024-08-03 10:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0002_workspace_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineManager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('positions_in_a_line', models.PositiveIntegerField(default=0)),
                ('average_serving_time', models.PositiveIntegerField(default=0)),
                ('ticket_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websocket.workspace')),
            ],
        ),
    ]
