# Generated by Django 4.1 on 2024-08-07 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0003_linemanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiting_time', models.PositiveIntegerField()),
                ('operation_time', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='websocket.workspace')),
            ],
        ),
    ]
